apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: final-project-eks-cluster-dev
  region: us-east-1
  version: '1.29'
    
iam:
  withOIDC: true

vpc:
  id: vpc-0043be5ba03ca6d29
  subnets:
    public:
      us-east-1a: { id: subnet-00bbc5bc469498850 }
      us-east-1b: { id: subnet-01b0b1da135fd16e9 }
      us-east-1c: { id: subnet-0944b1cd235e46e19 }
  securityGroup: sg-051a612e0dcd3f07c
      
nodeGroups:
  - name: final-project-eks-nodegroup
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 1
    maxSize: 5
    amiFamily: Ubuntu2204
    ami: ami-0e001c9271cf7f3b9  # Ubuntu 22.04 (x86)
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh final-project-eks-cluster-dev
    iam:
        attachPolicyARNs:
          - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
          - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
          - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
          - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
    ssh:
        allow: true
        publicKeyName: fp-eks-worker-node-key-pair
              