apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: stresspod
  name: stresspod
  namespace: myspace
spec:
  containers:
  - image: nginx
    name: stresspod
    resources: 
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
